/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Technician;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CommuterSystem.CommuterSystem;
import model.IssueManagement.Issue;
import model.LineManagement.Line;
import model.Personas.TechnicianProfile;

/**
 *
 * @author priyankbagad
 */
public class TechnicianViewIssues extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private CommuterSystem commuterSystem;
    private String technicianID;
    private Issue selectedIssue;
    /**
     * Creates new form TechnicianViewIssues
     */
    public TechnicianViewIssues(JPanel userProcessContainer,CommuterSystem commuterSystem, TechnicianProfile technicianProfile, Issue selectedIssue) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.commuterSystem = commuterSystem;
        this.technicianID = technicianProfile.getPerson().getId();
        this.selectedIssue = selectedIssue;
        populateIssueDetails();  // Populate fields with issue details
        setFieldsNonEditable(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnRessolve = new javax.swing.JButton();
        btnInprogress = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setText("Issue ID :");

        jLabel2.setText("Line Name");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Description :");

        jLabel4.setText("Status :");

        jLabel5.setText("Raised by :");

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRessolve.setText("Mark as Ressolved");
        btnRessolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRessolveActionPerformed(evt);
            }
        });

        btnInprogress.setText("Mark as In-progress");
        btnInprogress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInprogressActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblTitle.setText("VIEW ISSUES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnRessolve)
                                .addGap(38, 38, 38)
                                .addComponent(btnInprogress))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(jTextField2)
                                        .addComponent(jTextField3)
                                        .addComponent(jTextField4)
                                        .addComponent(jTextField5))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnBack)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRessolve)
                    .addComponent(btnInprogress))
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Remove the current panel from the container
        userProcessContainer.remove(this);

        // Refresh and navigate to the previous panel
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // Refresh the container to ensure proper layout update
        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRessolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRessolveActionPerformed
        selectedIssue.setStatus("Resolved");

    // Update line status to "Operational"
    Line line = commuterSystem.getLineDirectory().findLineByName(selectedIssue.getLineName());
    if (line != null) {
        line.setStatus("Operational");
    } else {
        JOptionPane.showMessageDialog(this, "Line not found for this issue.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Show confirmation message
    JOptionPane.showMessageDialog(this, "Issue marked as Resolved. Line status updated to Operational.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRessolveActionPerformed

    private void btnInprogressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInprogressActionPerformed
        selectedIssue.setStatus("In-Progress");

    // Update line status to "Delayed"
    Line line = commuterSystem.getLineDirectory().findLineByName(selectedIssue.getLineName());
    if (line != null) {
        line.setStatus("Delayed");
    } else {
        JOptionPane.showMessageDialog(this, "Line not found for this issue.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Show confirmation message
    JOptionPane.showMessageDialog(this, "Issue marked as In-Progress. Line status updated to Delayed.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInprogressActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInprogress;
    private javax.swing.JButton btnRessolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    private void populateIssueDetails() {
    if (selectedIssue != null) {
        jTextField1.setText(selectedIssue.getIssueID());
        jTextField2.setText(selectedIssue.getLineName());
        jTextField3.setText(selectedIssue.getDescription());
        jTextField4.setText(selectedIssue.getStatus());
        jTextField5.setText(selectedIssue.getRaisedBy());
    } else {
        JOptionPane.showMessageDialog(this, "No issue data available.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    private void setFieldsNonEditable() {
        if (selectedIssue != null) {
        jTextField1.setText(selectedIssue.getIssueID());
        jTextField2.setText(selectedIssue.getLineName());
        jTextField3.setText(selectedIssue.getDescription());
        jTextField4.setText(selectedIssue.getStatus());
        jTextField5.setText(selectedIssue.getRaisedBy());
    } else {
        JOptionPane.showMessageDialog(this, "No issue data available.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }

}

