/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import model.CommuterSystem.CommuterSystem;
import model.IssueManagement.Issue;
import model.Personas.TechnicianDirectory;
import model.Personas.TechnicianProfile;

/**
 *
 * @author rudra
 */
public class AssignIssueToTechnicianJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private CommuterSystem commuterSystem;
    private Issue issue;
    /**
     * Creates new form AssignIssueToTechnicianJPanel
     */
    public AssignIssueToTechnicianJPanel(JPanel userProcessContainer, CommuterSystem commuterSystem, Issue issue) {
        this.userProcessContainer = userProcessContainer;
        this.commuterSystem = commuterSystem;
        this.issue = issue;
        initComponents();
        populateFields();
        populateTechnicianComboBox();
        
    }

    private void populateFields() {
        txtIssueID.setText(issue.getIssueID());
        txtStationName.setText(issue.getLineName());
        txtDescription.setText(issue.getDescription());
        txtRaisedBy.setText(issue.getRaisedBy());
    }
    private void populateTechnicianComboBox() {
        TechnicianDirectory technicianDirectory = commuterSystem.getTechnicianDirectory();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        for (TechnicianProfile technicianProfile : technicianDirectory.getTechnicianList()) {
            model.addElement(technicianProfile.getPerson().getName());  // Assuming Person has a getName() method
        }
        jComboBox1.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblIssueID = new javax.swing.JLabel();
        lblStationName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblRaisedBy = new javax.swing.JLabel();
        txtIssueID = new javax.swing.JTextField();
        txtStationName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtRaisedBy = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblChooseTechnician = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblIssueID.setText("Issue ID");

        lblStationName.setText("Line Name");

        lblDescription.setText("Description");

        lblRaisedBy.setText("Raised By");

        txtIssueID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIssueIDActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblChooseTechnician.setText("Choose Technician");

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblTitle.setText("ASSIGN ISSUE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnBack)
                        .addGap(95, 95, 95)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIssueID)
                            .addComponent(lblStationName)
                            .addComponent(lblDescription)
                            .addComponent(lblRaisedBy)
                            .addComponent(lblChooseTechnician))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRaisedBy)
                            .addComponent(txtDescription)
                            .addComponent(txtIssueID, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtStationName)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnAssign)))
                .addContainerGap(339, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblChooseTechnician, lblDescription, lblIssueID, lblRaisedBy, lblStationName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDescription, txtIssueID, txtRaisedBy, txtStationName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblChooseTechnician)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(lblTitle))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIssueID)
                            .addComponent(txtIssueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStationName)
                            .addComponent(txtStationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescription)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaisedBy)
                            .addComponent(txtRaisedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(btnAssign)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Remove the current panel from the container
        userProcessContainer.remove(this);

        // Refresh and navigate to the previous panel
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // Refresh the container to ensure proper layout update
        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtIssueIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssueIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssueIDActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        String selectedTechnicianName = (String) jComboBox1.getSelectedItem();
        TechnicianDirectory technicianDirectory = commuterSystem.getTechnicianDirectory();
        TechnicianProfile selectedTechnicianProfile = null;
        
        // Find TechnicianProfile by name
        for (TechnicianProfile technicianProfile : technicianDirectory.getTechnicianList()) {
            if (technicianProfile.getPerson().getName().equals(selectedTechnicianName)) {
                selectedTechnicianProfile = technicianProfile;
                break;
            }
        }

        if (selectedTechnicianProfile != null) {
            issue.setAssignedTo(selectedTechnicianProfile);  // Set the technician profile to the issue
            issue.setStatus("Assigned");
            populateIssueTable();
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
            userProcessContainer.revalidate();
            userProcessContainer.repaint();
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void populateIssueTable() {
        // Refresh the issue table in the previous panel
        AdminTechnicianManagementJPanel previousPanel = (AdminTechnicianManagementJPanel) userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 2);
        previousPanel.populateIssueTable();
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblChooseTechnician;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblIssueID;
    private javax.swing.JLabel lblRaisedBy;
    private javax.swing.JLabel lblStationName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtIssueID;
    private javax.swing.JTextField txtRaisedBy;
    private javax.swing.JTextField txtStationName;
    // End of variables declaration//GEN-END:variables
}
