/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CommuterSystem.CommuterSystem;
import model.LineManagement.Line;
import model.Personas.StaffProfile;

/**
 *
 * @author rudra
 */
public class AssignLineToStaffJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private CommuterSystem commuterSystem;
    private Line selectedLine;
    private AdminStaffManagementJPanel parentPanel;
    /**
     * Creates new form AssignLineToStaffJPanel
     */
    public AssignLineToStaffJPanel(JPanel userProcessContainer, CommuterSystem commuterSystem, Line selectedLine, AdminStaffManagementJPanel parentPanel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.commuterSystem = commuterSystem;
        this.selectedLine = selectedLine;
        this.parentPanel = parentPanel;
        populateLineDetails();
        populateStaffDropdown();
    }
    private void populateLineDetails() {
        txtLineID.setText(selectedLine.getLineId());
        txtStart.setText(selectedLine.getStartStation());
        txtDestination.setText(selectedLine.getEndStation());
        txtDutyHours.setText(String.valueOf(selectedLine.getDutyHours()));

        txtLineID.setEditable(false);
        txtStart.setEditable(false);
        txtDestination.setEditable(false);
        txtDutyHours.setEditable(false);
    }
    private void populateStaffDropdown() {
        jComboBox1.removeAllItems();
    List<StaffProfile> staffList = commuterSystem.getStaffDirectory().getStaffList();
    for (StaffProfile staff : staffList) {
        jComboBox1.addItem(staff.getPerson().getName());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStart = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtDutyHours = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblChooseStaff = new javax.swing.JLabel();
        lblLineID = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        lblDutyHours = new javax.swing.JLabel();
        txtLineID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblChooseStaff.setText("Choose Staff");

        lblLineID.setText("Line ID");

        lblStart.setText("Start Station");

        lblDestination.setText("Destination");

        lblDutyHours.setText("Duty Hours");

        txtLineID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLineIDActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblTitle.setText("ASSIGN STAFF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnBack)
                        .addGap(97, 97, 97)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDestination, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblChooseStaff, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDutyHours, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblLineID)
                                        .addComponent(lblStart)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDutyHours, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLineID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnAssign)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLineID)
                    .addComponent(txtLineID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStart))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestination)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDutyHours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDutyHours, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChooseStaff))
                .addGap(27, 27, 27)
                .addComponent(btnAssign)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtLineIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLineIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLineIDActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Remove the current panel from the container
        userProcessContainer.remove(this);

        // Refresh and navigate to the previous panel
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // Refresh the container to ensure proper layout update
        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        String selectedStaffName = (String) jComboBox1.getSelectedItem();
    if (selectedStaffName == null) {
        JOptionPane.showMessageDialog(null, "Please select a staff.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Find the selected staff using the new method
    StaffProfile selectedStaff = commuterSystem.getStaffDirectory().findStaffByName(selectedStaffName);
    if (selectedStaff == null) {
        JOptionPane.showMessageDialog(null, "Selected staff not found.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Assign the staff to the line
    selectedLine.setAssignedStaff(selectedStaff);

    JOptionPane.showMessageDialog(null, "Staff assigned successfully!");

    // Refresh the parent panel's table
    parentPanel.populateTable();

    // Navigate back to AdminStaffManagementJPanel
    btnBackActionPerformed(evt);
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblChooseStaff;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblDutyHours;
    private javax.swing.JLabel lblLineID;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtDutyHours;
    private javax.swing.JTextField txtLineID;
    private javax.swing.JTextField txtStart;
    // End of variables declaration//GEN-END:variables
}
