/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Staff;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CommuterSystem.CommuterSystem;
import model.IssueManagement.Issue;



/**
 *
 * @author manas
 */
public class StaffIssueJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private CommuterSystem commuterSystem;
    /**
     * Creates new form StaffIssueJPanel
     */
    public StaffIssueJPanel(JPanel userProcessContainer, CommuterSystem commuterSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.commuterSystem = commuterSystem;
        populatePriorityComboBox();

    }
    
       private void populatePriorityComboBox() {
        jComboPriority.removeAllItems(); // Clear existing items
        jComboPriority.addItem("High");
        jComboPriority.addItem("Medium");
        jComboPriority.addItem("Low");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblIssuetitle = new javax.swing.JLabel();
        txtIssueID = new javax.swing.JTextField();
        lblIssueDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaDesc = new javax.swing.JTextArea();
        lblIssueID = new javax.swing.JLabel();
        txtTitle1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lblssuePriority = new javax.swing.JLabel();
        jComboPriority = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        btnRaise = new javax.swing.JButton();

        jLabel5.setText("Raised by :");

        jTextField5.setText("jTextField5");

        setBackground(new java.awt.Color(255, 255, 153));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblTitle.setText("Raise Issue");

        lblIssuetitle.setText("Title");

        txtIssueID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIssueIDActionPerformed(evt);
            }
        });

        lblIssueDescription.setText("Description");

        txtareaDesc.setColumns(20);
        txtareaDesc.setRows(5);
        jScrollPane2.setViewportView(txtareaDesc);

        lblIssueID.setText("Issue Id");

        txtTitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitle1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Line Name");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        lblssuePriority.setText("Priority");

        jComboPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High"}));
        jComboPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPriorityActionPerformed(evt);
            }
        });

        jLabel6.setText("Raised by ");

        btnRaise.setText("Raise");
        btnRaise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIssueDescription)
                                    .addComponent(lblIssuetitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(lblTitle))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(txtTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                            .addComponent(jComboPriority, 0, 120, Short.MAX_VALUE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addComponent(jTextField2)
                                            .addComponent(txtIssueID, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))))
                            .addComponent(lblIssueID)
                            .addComponent(lblssuePriority, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(btnRaise)))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel6, lblIssueDescription, lblIssueID, lblIssuetitle, lblssuePriority});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboPriority, jTextField2, jTextField6, txtIssueID, txtTitle1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIssueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIssueID))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIssuetitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIssueDescription)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblssuePriority))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnRaise)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Check if userProcessContainer is initialized
    if (userProcessContainer != null) {
        // Remove the current panel
        userProcessContainer.remove(this);

        // Refresh and navigate to the previous panel
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // Refresh the container to ensure proper layout update
        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    } else {
        System.out.println("Error: userProcessContainer is not initialized.");
    }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtIssueIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssueIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssueIDActionPerformed

    private void txtTitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitle1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPriorityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboPriorityActionPerformed

    private void btnRaiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseActionPerformed
        if (commuterSystem == null) {
        JOptionPane.showMessageDialog(this, "System error: CommuterSystem is not initialized.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String issueID = txtIssueID.getText().trim();
    String title = txtTitle1.getText().trim();
    String description = txtareaDesc.getText().trim();
    String priority = (String) jComboPriority.getSelectedItem();
    String stationName = jTextField2.getText().trim();
    String raisedBy = jTextField6.getText().trim();

    if (issueID.isEmpty() || title.isEmpty() || description.isEmpty() || stationName.isEmpty() || raisedBy.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Create and add the issue
    Issue newIssue = new Issue(issueID, stationName, description, "Open", raisedBy);
    newIssue.setTitle(title);
    newIssue.setPriority(priority);
    commuterSystem.getIssueDirectory().addIssue(newIssue);

    JOptionPane.showMessageDialog(this, "Issue raised successfully!");

    // Clear the form fields
    txtIssueID.setText("");
    txtTitle1.setText("");
    txtareaDesc.setText("");
    jTextField2.setText("");
    jTextField6.setText("");
    jComboPriority.setSelectedIndex(0);

    btnBackActionPerformed(evt); // Navigate back to the previous panel
    }//GEN-LAST:event_btnRaiseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRaise;
    private javax.swing.JComboBox<String> jComboPriority;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblIssueDescription;
    private javax.swing.JLabel lblIssueID;
    private javax.swing.JLabel lblIssuetitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblssuePriority;
    private javax.swing.JTextField txtIssueID;
    private javax.swing.JTextField txtTitle1;
    private javax.swing.JTextArea txtareaDesc;
    // End of variables declaration//GEN-END:variables
}
