/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Staff;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import model.CommuterSystem.CommuterSystem;
import model.IssueManagement.*;
import model.LineManagement.Line;
import model.LineManagement.LineDirectory;
import model.Personas.StaffProfile;

/**
 *
 * @author manas
 */
public class StaffScheduleJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
      private JTable scheduleTable;
    private StaffProfile loggedInStaff;
    private DefaultTableModel tableModel;
    private IssueDirectory issueDirectory;
    private LineDirectory lineDirectory;
    private CommuterSystem commuterSystem;
    
    /**

    /**
     * Creates new form StaffScheduleJPanel
     */
    public StaffScheduleJPanel(JPanel userProcessContainer, LineDirectory lineDirectory, StaffProfile loggedInStaff, CommuterSystem commuterSystem) {
    
    this.userProcessContainer = userProcessContainer;
    this.loggedInStaff = loggedInStaff;
    this.lineDirectory = lineDirectory;
    this.commuterSystem = commuterSystem;
    
    initComponents();
    
    
     
    populateStaffScheduleTable();
}

    
    
     

    private void populateStaffScheduleTable() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0); // Clear existing rows

        ArrayList<Line> assignedLines = lineDirectory.getLinesAssignedToStaff(loggedInStaff);
        if (assignedLines == null || assignedLines.isEmpty()) {
            System.out.println("No lines found for the logged-in staff!");
            return;
        }

        for (Line line : assignedLines) {
            tableModel.addRow(new Object[]{
                line.getLineId(),
                line.getLineName(),
                line.getStartStation(),
                line.getEndStation(),
                line.getAssignedStaff().getPerson().getName() // Staff name
            });
        }
        tableModel.fireTableDataChanged();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        BtnIssue = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 153));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblTitle.setText("Today's Schedule");

        BtnIssue.setText("Raise Issue");
        BtnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIssueActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Line_ID", "Line Name", "Start Station", "End Station", "Assigned To"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(BtnIssue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(BtnIssue)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Remove the current panel from the container
        if (userProcessContainer != null) {
        // Remove the current panel
        userProcessContainer.remove(this);

        // Refresh and navigate to the previous panel
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // Refresh the container to ensure proper layout update
        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    } else {
        System.out.println("Error: userProcessContainer is not initialized.");
    }
    }//GEN-LAST:event_btnBackActionPerformed

    private void BtnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIssueActionPerformed
        // TODO add your handling code here:
         if (userProcessContainer != null) {
        // Create an instance of StaffIssueJPanel with CommuterSystem
        StaffIssueJPanel issuePanel = new StaffIssueJPanel(userProcessContainer, commuterSystem);

        // Add the panel to the container
        userProcessContainer.add("StaffIssueJPanel", issuePanel);

        // Switch to StaffIssueJPanel
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        // Refresh the container
        userProcessContainer.revalidate();
        userProcessContainer.repaint();
    } else {
        System.out.println("Error: userProcessContainer is not initialized.");
    }
    }//GEN-LAST:event_BtnIssueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIssue;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
